//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesSet
    {
        public CategoriesSet()
        {
            this.ProductsSet = new HashSet<ProductsSet>();
            this.SectionsSet = new HashSet<SectionsSet>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<ProductsSet> ProductsSet { get; set; }
        public virtual ICollection<SectionsSet> SectionsSet { get; set; }
        public override string ToString()
        {
            return   Nom  ;
        }
    }
}
