//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesSet
    {
        public EmployeesSet()
        {
            this.CheckoutSet = new HashSet<CheckoutSet>();
            this.SectionsSet = new HashSet<SectionsSet>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
    
        public virtual ICollection<CheckoutSet> CheckoutSet { get; set; }
        public virtual ICollection<SectionsSet> SectionsSet { get; set; }
        public override string ToString()
        { 
            return Id + "-" +Nom + "-" + Prenom;
        }
    }
}
