//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsSet
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public bool CheckEmpty { get; set; }
        public int Prix { get; set; }
        public int CategoriesId { get; set; }
    
        public virtual CategoriesSet CategoriesSet { get; set; }
    }
}
